# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
#Loom
loom_version=1.7-SNAPSHOT
#Modrinth
modrinth_versions=["1.21", "1.21.1"]
#CurseForge
curseforge_id=413596
#Dependencies
required_dependencies=["fabric-api", "worldweaver", "bclib"]
#optional_dependencies=["patchouli", "trinkets", "emi", "modmenu"]
optional_dependencies=["emi", "modmenu", "trinkets"]
#`release`, `beta` or `alpha`
release_channel=alpha
modrinth_id=betterend
# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.1
loader_version=0.16.0
fabric_version=0.102.0+1.21.1
# Mod Properties
mod_version=21.0.12
maven_group=org.betterx
archives_base_name=better-end
# Dependencies
bclib_version=21.0.13
wover_version=21.0.13
wunderlib_version=21.0.8
patchouli_version=1.19-73-FABRIC
jade_version=15.10.2+fabric
rei_version=16.0.744
emi_version=1.1.22+1.21.1+fabric
trinkets_version=3.10.0
cca_version=6.1.1
modmenu_version=11.0.1